"""p4_preference_signals

Revision ID: 5a396a1c513b
Revises: e26e196b8532
Create Date: 2026-07-19 09:22:01.908081
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a396a1c513b'
down_revision: Union[str, None] = 'e26e196b8532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('creative_doc_id', sa.String(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('reason_tag', sa.String(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preference_signals_client_id'), 'preference_signals', ['client_id'], unique=False)
    op.create_index(op.f('ix_preference_signals_creative_doc_id'), 'preference_signals', ['creative_doc_id'], unique=False)
    op.create_index(op.f('ix_preference_signals_job_id'), 'preference_signals', ['job_id'], unique=False)
    op.create_index(op.f('ix_preference_signals_tenant_id'), 'preference_signals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preference_signals_tenant_id'), table_name='preference_signals')
    op.drop_index(op.f('ix_preference_signals_job_id'), table_name='preference_signals')
    op.drop_index(op.f('ix_preference_signals_creative_doc_id'), table_name='preference_signals')
    op.drop_index(op.f('ix_preference_signals_client_id'), table_name='preference_signals')
    op.drop_table('preference_signals')
    # ### end Alembic commands ###
