"""P1 pillars + job.pillar_id

Revision ID: a994b6944e9a
Revises: 649d3966fd75
Create Date: 2026-07-18 23:13:28.005813
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a994b6944e9a'
down_revision: Union[str, None] = '649d3966fd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_pillars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pillars_client_id'), 'content_pillars', ['client_id'], unique=False)
    op.create_index(op.f('ix_content_pillars_tenant_id'), 'content_pillars', ['tenant_id'], unique=False)
    op.add_column('jobs', sa.Column('pillar_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'pillar_id')
    op.drop_index(op.f('ix_content_pillars_tenant_id'), table_name='content_pillars')
    op.drop_index(op.f('ix_content_pillars_client_id'), table_name='content_pillars')
    op.drop_table('content_pillars')
    # ### end Alembic commands ###
