"""p5_client_email_unique

Revision ID: f05cd87bcf42
Revises: 5a396a1c513b
Create Date: 2026-07-19 12:59:24.113267
"""
from typing import Sequence, Union

from alembic import op


revision: str = 'f05cd87bcf42'
down_revision: Union[str, None] = '5a396a1c513b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_clients_tenant_email', 'clients', ['tenant_id', 'contact_email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_clients_tenant_email', 'clients', type_='unique')
    # ### end Alembic commands ###
